select
    _ID,
    AGENT_EMAIL, 
    AGENT_FIRST_NAME, 
    AGENT_LAST_NAME, 
    DESTINATION, 
    DURATION_MINUTES, 
    EQUIPMENT, 
    FLIGHT_CODE, 
    FLIGHT_DATE, 
    FLIGHT_ID, 
    FLOW_PUBLISHED_AT, 
    GATE, 
    ORIGIN, 
    PASSENGERS, 
    SEATS_AVAILABLE    
from 
    {{source('airline_flights_data_source','flights')}}